### ISSUE TITLE
Speed and binary size of this library?

### ISSUE THREAD

**Issue by fzyzcjy** [kornelski/lodepng-rust#49]
Hi thanks for this wonderful lib! I wonder (1) how fast is it, and (2) how big is the generated binary executable, compared with traditional libpng? Thank you!

**Comment by kornelski** [comment]
To be honest, it's not great. 

It's a straightforward translation of simple C code. It doesn't have low-level optimizations and I haven't checked if it autovectorizes (probably not).

I use it mainly because libpng as a dependency is endless suffering due to old versions being kept alive by Linux distros, and difficulty in statically vs dynamically linking libpng vs zlib as appropriate for each OS/distro (cmake chokes on it, pkg-config file may sabotage static linking, etc.)

**Comment by fzyzcjy** [comment]
Thank you!
